# Data Merging Part 2.

In [1]:
# pandas
import pandas as pd

In [2]:
# import the modified dataset from part 1
popped_df = pd.read_csv('./archive/AthletesWithPopulations.csv',index_col=False)

# import the datasets still needed
lifex_df = pd.read_csv('./archive/life_expectancy.csv')
ruralperc_df = pd.read_csv('./archive/RuralPopperc.csv')
gdp_df = pd.read_csv('./archive/GDP.csv')

In [3]:
popped_df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal,Host,Nat_Pop,Global_Pop%
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN,0,1.164970e+09,0.213515
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN,0,1.350695e+09,0.190308
2,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NLD,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN,0,1.476009e+07,0.002891
3,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NLD,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN,0,1.476009e+07,0.002891
4,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NLD,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN,0,1.518417e+07,0.002783

In [4]:
# attach the rural population percentage data to the dataframe
rur_pop = []
for index, row in popped_df.iterrows():
    NOC = row['NOC']
    year = str(row['Year']) 
    ref_df = ruralperc_df[ruralperc_df['Country Code'] == NOC]
    rpop = ref_df[year].iat[0]
    rur_pop.append(rpop)
popped_df['Rural_Pop%'] = rur_pop

In [5]:
# attach the life expectancy data to the dataframe
life_ex = []
for index, row in popped_df.iterrows():
    NOC = row['NOC']
    year = str(row['Year']) 
    ref_df = lifex_df[lifex_df['Country Code'] == NOC]
    lifex = ref_df[year].iat[0]
    life_ex.append(lifex)
popped_df['Life_Expect'] = life_ex

In [6]:
# attach the life expectancy data to the dataframe
gdp = []
for index, row in popped_df.iterrows():
    NOC = row['NOC']
    year = str(row['Year']) 
    ref_df = gdp_df[gdp_df['Country Code'] == NOC]
    gross = ref_df[year].iat[0]
    gdp.append(gross)
popped_df['GDP'] = gdp

In [7]:
data = popped_df
data.to_csv('./archive/Data.csv')