In [4]:
import pandas as pd

In [5]:
gdp_df = pd.read_csv('./archive/GDP.csv')
data_df = pd.read_csv('./archive/Data.csv')

In [6]:
# attach the GDP percent of global
glob_gdp_perc = []
gdp_df = gdp_df[gdp_df['Country Code'] == 'WLD']
for index, row in data_df.iterrows():
    NOC = row['NOC']
    year = str(row['Year'])
    ngdp = row['GDP']
    ref_df = gdp_df[gdp_df['Country Code'] == NOC]
    ggdp = gdp_df[year].iat[0]
    glob_gdp_perc.append(ngdp/ggdp)
data_df['Global_GDP%'] = glob_gdp_perc

In [7]:
data_df.head()

,Unnamed: 0,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,...,Event,Medal,Host,Nat_Pop,Global_Pop%,Rural_Pop%,Life_Expect,GDP,GDP_Per_Cap,Global_GDP%
0,0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,...,Basketball Men's Basketball,NaN,0,1.164970e+09,0.213515,71.800,69.587000,4.270000e+11,366.5330438,0.016811
1,1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,...,Judo Men's Extra-Lightweight,NaN,0,1.350695e+09,0.190308,48.111,75.602000,8.560000e+12,6337.478113,0.114286
2,2,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NLD,1988 Winter,...,Speed Skating Women's 500 metres,NaN,0,1.476009e+07,0.002891,32.094,76.890244,2.590000e+11,17547.31372,0.013560
3,3,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NLD,1988 Winter,...,"Speed Skating Women's 1,000 metres",NaN,0,1.476009e+07,0.002891,32.094,76.890244,2.590000e+11,17547.31372,0.013560
4,4,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NLD,1992 Winter,...,Speed Skating Women's 500 metres,NaN,0,1.518417e+07,0.002783,29.777,77.217073,3.580000e+11,23577.19219,0.014094

In [8]:
data_df.to_csv('./archive/Data.csv')